# Generated by Django 5.0.7 on 2024-07-23 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('total', models.FloatField()),
                ('createt_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='comida.producto')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
