# Generated by Django 5.0.7 on 2024-07-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0003_remove_pedido_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('totalPedido', models.FloatField(default=0)),
                ('fechaHora', models.DateTimeField()),
                ('totalItems', models.IntegerField(default=0)),
                ('createt_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datospedidos',
            },
        ),
        migrations.CreateModel(
            name='ItemsPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.FloatField()),
                ('total', models.FloatField()),
                ('createt_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('envioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datospedidos', to='comida.datospedido')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='comida.producto')),
            ],
            options={
                'db_table': 'itemspedidos',
            },
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
