# Generated by Django 5.0.7 on 2024-07-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_rename_envioid_itemspedido_datospedidoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemspedido',
            old_name='DatosPedidoId',
            new_name='datosPedidoId',
        ),
    ]
